from django.urls import path

from .views import (
    DailyStatsView,
    DashboardCategoryView,
    DashboardView,
    FinancialEntryCreateView,
    FinancialEntryDetailView,
    FinancialEntryListView,
    MonthlyStatsView,
    PlannedIncomeCreateView,
    PlannedIncomeDetailView,
    PlannedIncomeListView,
    PlannedReserveCreateView,
    PlannedReserveDetailView,
    PlannedReserveListView,
    PhoneLoginView,
    PlannerCreateView,
    PlannerDetailView,
    PlannerListView,
    ValidatePhoneView,
    WeeklyStatsView,
)

urlpatterns = [
    path("validate-phone/", ValidatePhoneView.as_view()),
    path("financial-entry/", FinancialEntryCreateView.as_view()),
    path("login/", PhoneLoginView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("entries/", FinancialEntryListView.as_view()),
    path("entries/<int:entry_id>/", FinancialEntryDetailView.as_view()),
    path("dashboard/categories/", DashboardCategoryView.as_view()),
    path("planner/", PlannerListView.as_view()),
    path("planner/create/", PlannerCreateView.as_view()),
    path("planner/<int:expense_id>/", PlannerDetailView.as_view()),
    path("fixed-incomes/", PlannedIncomeListView.as_view()),
    path("fixed-incomes/create/", PlannedIncomeCreateView.as_view()),
    path("fixed-incomes/<int:income_id>/", PlannedIncomeDetailView.as_view()),
    path("reserves/", PlannedReserveListView.as_view()),
    path("reserves/create/", PlannedReserveCreateView.as_view()),
    path("reserves/<int:reserve_id>/", PlannedReserveDetailView.as_view()),
    path("stats/daily/", DailyStatsView.as_view()),
    path("stats/weekly/", WeeklyStatsView.as_view()),
    path("stats/monthly/", MonthlyStatsView.as_view()),
]
