from django.urls import path

from .views import (
    CreditCardCreateView,
    CreditCardDetailView,
    CreditCardExpenseCreateView,
    CreditCardExpenseDetailView,
    CreditCardExpenseListView,
    CreditCardListView,
    CreditCardSummaryView,
    DailyStatsView,
    DashboardCategoryView,
    DashboardView,
    FinancialEntryCreateView,
    FinancialEntryDetailView,
    FinancialEntryListView,
    FinancialEntryReceiptView,
    MonthlyStatsView,
    PlannedIncomeCreateView,
    PlannedIncomeDetailView,
    PlannedIncomeListView,
    PlannedReserveCreateView,
    PlannedReserveDetailView,
    PlannedReserveListView,
    PhoneLoginView,
    ProfileView,
    PlannerCreateView,
    PlannerDetailView,
    PlannerListView,
    RegisterView,
    ValidatePhoneView,
    VehicleCreateView,
    VehicleDetailView,
    VehicleExpenseCreateView,
    VehicleExpenseDetailView,
    VehicleExpenseListView,
    VehicleListView,
    VehicleSummaryView,
    WhatsAppSummaryWebhookView,
    WeeklyStatsView,
    UserManualPdfView,
)

urlpatterns = [
    path("validate-phone/", ValidatePhoneView.as_view()),
    path("register/", RegisterView.as_view()),
    path("financial-entry/", FinancialEntryCreateView.as_view()),
    path("login/", PhoneLoginView.as_view()),
    path("profile/", ProfileView.as_view()),
    path("profile/manual-pdf/", UserManualPdfView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("entries/", FinancialEntryListView.as_view()),
    path("entries/<int:entry_id>/", FinancialEntryDetailView.as_view()),
    path("entries/<int:entry_id>/receipt/", FinancialEntryReceiptView.as_view()),
    path("dashboard/categories/", DashboardCategoryView.as_view()),
    path("planner/", PlannerListView.as_view()),
    path("planner/create/", PlannerCreateView.as_view()),
    path("planner/<int:expense_id>/", PlannerDetailView.as_view()),
    path("fixed-incomes/", PlannedIncomeListView.as_view()),
    path("fixed-incomes/create/", PlannedIncomeCreateView.as_view()),
    path("fixed-incomes/<int:income_id>/", PlannedIncomeDetailView.as_view()),
    path("reserves/", PlannedReserveListView.as_view()),
    path("reserves/create/", PlannedReserveCreateView.as_view()),
    path("reserves/<int:reserve_id>/", PlannedReserveDetailView.as_view()),
    path("vehicles/", VehicleListView.as_view()),
    path("vehicles/create/", VehicleCreateView.as_view()),
    path("vehicles/<int:vehicle_id>/", VehicleDetailView.as_view()),
    path("vehicle-expenses/", VehicleExpenseListView.as_view()),
    path("vehicle-expenses/create/", VehicleExpenseCreateView.as_view()),
    path("vehicle-expenses/<int:expense_id>/", VehicleExpenseDetailView.as_view()),
    path("vehicles/summary/", VehicleSummaryView.as_view()),
    path("credit-cards/", CreditCardListView.as_view()),
    path("credit-cards/create/", CreditCardCreateView.as_view()),
    path("credit-cards/<int:card_id>/", CreditCardDetailView.as_view()),
    path("credit-card-expenses/", CreditCardExpenseListView.as_view()),
    path("credit-card-expenses/create/", CreditCardExpenseCreateView.as_view()),
    path("credit-card-expenses/<int:expense_id>/", CreditCardExpenseDetailView.as_view()),
    path("credit-cards/summary/", CreditCardSummaryView.as_view()),
    path("stats/daily/", DailyStatsView.as_view()),
    path("stats/weekly/", WeeklyStatsView.as_view()),
    path("stats/monthly/", MonthlyStatsView.as_view()),
    path("whatsapp-summary/", WhatsAppSummaryWebhookView.as_view()),
]
